swagger: '2.0'
info:
  version: 0.0.1
  title: "Esercizio 3"
  description: "API per la gestione di serie tv"

paths:
  /serie/:
    get:
      description: "Ottenere l'elenco di tutte le serie TV di un dato genere e pubblicate dopo una data specificata"
      operationId: getEpisodeByGenereAndData
      parameters:
        - name: dataPubb
          in: query
          type: string
          required: true
        - name: genere
          in: query
          required: true
          type: string
          enum:
            - "animazione"
            - "avventura"
            - "commedia"
            - "azione"
            - "documentario"
      responses:
        200:
          description: "Retrieved"
          schema:
            type: array
            items: 
              $ref: "#/definitions/Serie"
        400:
          description: "I parametri in input non sono corretti"

  /serie/{idSerie}/episodi/:
    post:
      description: "Aggiungere un nuovo episodio ad una serie TV"
      operationId: addEpisodeById
      parameters:
        - name: idSerie
          in: path
          type: string
          required: true
        - in: body
          name: episodio
          required: true
          schema:
            $ref: "#/definitions/Episodio"
      responses:
        200:
          description: "Episodio aggiunto"
        400:
          description: "I parametri in input non sono corretti"

  /serie/{idSerie}/episodi/{numero}:
    put:
      description: "modificare il titolo di uno specifico episodio di una serie TV"
      operationId: setTitleEpisodeById
      parameters:
        - name: idSerie
          in: path
          type: string
          required: true
        - name: numero
          in: path
          type: integer
          required: true
        - in: body
          name: titolo
          required: true
          schema:
            type: object
            properties:
              titolo:
                type: string
      responses:
        200:
          description: "Titolo episodio modificato"
        400:
          description: "I parametri in input non sono corretti"

definitions:
  Serie:
    type: object
    required:
      - id
      - titolo
      - dataPubb
      - genere
      - episodi
    properties:
      id:
        type: string
        example: "S0001"
        description: "ID della serie tv"
      titolo:
        type: string
        example: "Diavoli"
        description: "il nome della serie tv"
      dataPubb:
        type: string
        format: date
        example: "2022-01-01"
        description: "Data di pubblicazione della serie"
      genere:
        type: string
        enum:
          - "animazione"
          - "avventura"
          - "commedia"
          - "azione"
          - "documentario"
        example: "animazione"
        description: "Genere della serie"
      episodi:
        type: array
        items:
          $ref: "#/definitions/Episodio"

  Episodio:
    type: object
    required:
      - numero
      - titolo
    properties:
      numero:
        type: integer
        example: 10
        description: "Numero della puntata"
      titolo:
        type: string
        example: "Il ritorno in Italia"
        description: "Titolo della puntata"


